// Learning Center content for the AI Governance Homelab. Pure data - no API calls, no mutations.
// Each stage is one object starting with `{ n:` so tests can check it. PLANNED stages must not have links.
export type GuideStatus = "AVAILABLE" | "PLANNED";
export type GuideLink = { label: string; href: string };
export type GuideStage = {
  n: number;
  title: string;
  status: GuideStatus;
  what: string;
  why: string;
  area: string;
  links: GuideLink[];
  human: string;
  output: string;
  next: string;
  note?: string;
};

export const HUMAN_AUTHORITY = "AI ASSISTS. HUMANS GOVERN.";

export const AI_GOVERNANCE_STAGES: GuideStage[] = [
  { n: 1, title: "Discover / Identify AI", status: "AVAILABLE",
    what: "Recognise that an AI system, model, service, application or agent exists and may need governance.",
    why: "You cannot govern AI you do not know about. Unknown (\"shadow\") AI is unmanaged risk.",
    area: "AI Inventory (manual identification)", links: [{ label: "Open AI Inventory", href: "/ai-inventory" }],
    human: "A person identifies the AI and decides it belongs in governance scope.",
    output: "A candidate AI system to register.", next: "Register the AI system.",
    note: "Automated AI discovery (a future Registrar Agent) is a planned capability and is not built yet - identification is manual today." },
  { n: 2, title: "Register AI System", status: "AVAILABLE",
    what: "Add the AI system to the authoritative AI Inventory: name, owner, origin (internal or third-party), lifecycle, business criticality, data sensitivity and basic governance metadata.",
    why: "The inventory is the single record everything else attaches to - assessments, controls, evidence, findings and monitoring.",
    area: "AI Inventory", links: [{ label: "Register an AI system", href: "/ai-inventory" }],
    human: "The registrant records accurate facts; the owner confirms them.",
    output: "An AI system record.", next: "Define how the AI is used." },
  { n: 3, title: "Define AI Use Case", status: "AVAILABLE",
    what: "Describe what the AI does, who uses it, the business purpose, affected people, decisions it supports or automates, data involved and the expected outcome.",
    why: "The same model can be low-risk in one use and high-risk in another. Risk follows the use case.",
    area: "AI Use Cases", links: [{ label: "Open AI Use Cases", href: "/ai-use-cases" }],
    human: "The business owner states the intended use and its limits; a separate human reviewer approves it.",
    output: "A documented use case per AI system.", next: "Assign accountable ownership.",
    note: "Each use case belongs to one AI system. In this version, risk and impact assessments are still performed on the AI system, with the use case as business context." },
  { n: 4, title: "Assign Ownership", status: "AVAILABLE",
    what: "Name the accountable owner for the AI system, and owners for its risk treatments, controls and monitoring checks.",
    why: "Governance needs a named human who answers for the AI - not a team, not a tool.",
    area: "AI system page (Governance owner, control owners, treatment and monitoring owners)", links: [{ label: "Open AI Inventory", href: "/ai-inventory" }],
    human: "A tenant member is assigned and accepts accountability.",
    output: "Owner recorded on the AI system and its governance records.", next: "Classify the AI." },
  { n: 5, title: "Classify AI", status: "AVAILABLE",
    what: "Classify by business criticality, impact level, data sensitivity, lifecycle/deployment status, decision role and human oversight.",
    why: "Classification decides how much governance depth the AI needs.",
    area: "AI system page - Governance profile", links: [{ label: "Open AI Inventory", href: "/ai-inventory" }],
    human: "An authorised analyst or administrator sets the classification.",
    output: "A governance profile and derived assessment posture.", next: "Assess AI risk." },
  { n: 6, title: "AI Risk Assessment", status: "AVAILABLE",
    what: "Identify risks, score inherent risk, record existing controls and their effectiveness, and determine residual risk and planned treatment.",
    why: "Shows what could go wrong, how likely and how severe - before and after controls.",
    area: "AI Risk Assessments", links: [{ label: "Go to Risk Assessments", href: "/risk-assessments" }, { label: "Risk Register", href: "/risk-register" }],
    human: "An assessor builds it; an independent reviewer approves it. The assessor cannot review their own work (separation of duties).",
    output: "A versioned, reviewed risk assessment.", next: "Assess impact." },
  { n: 7, title: "AI Impact Assessment", status: "AVAILABLE",
    what: "Assess potential effects on people, the business, privacy and data, legal and regulatory obligations, operations and reputation.",
    why: "Risk is about the organisation; impact also asks who could be harmed and how.",
    area: "AI Impact Assessments", links: [{ label: "Go to Impact Assessments", href: "/impact-assessments" }],
    human: "An assessor documents impacts; an independent reviewer approves.",
    output: "A versioned, reviewed impact assessment.", next: "Decide which frameworks apply." },
  { n: 8, title: "Determine Framework Applicability", status: "AVAILABLE",
    what: "Decide which requirements apply to this AI system - for example NIST AI RMF, ISO/IEC 42001, ISO/IEC 23894 or the EU AI Act - with a rationale.",
    why: "Not every framework applies to every AI. Applicability is a recorded decision, not an assumption.",
    area: "AI system page - Framework applicability; Compliance Frameworks library", links: [{ label: "Compliance Frameworks", href: "/frameworks" }],
    human: "An authorised analyst records the applicability decision and rationale.",
    output: "Applicable / not applicable decisions per framework.", next: "Map controls." },
  { n: 9, title: "Map AI Controls", status: "AVAILABLE",
    what: "Turn applicable requirements into controls for this AI system - human oversight, access control, documentation, monitoring, data governance, risk management, testing.",
    why: "Controls are how requirements become concrete, assignable work.",
    area: "AI system page - Controls", links: [{ label: "Open AI Inventory", href: "/ai-inventory" }],
    human: "Each control gets an owner and an applicability decision.",
    output: "A control set for the AI system.", next: "Collect evidence." },
  { n: 10, title: "Collect Evidence", status: "AVAILABLE",
    what: "Attach proof that controls exist: policies, screenshots, configurations, logs, assessment records, approvals, technical documentation.",
    why: "A control without evidence is only a claim.",
    area: "AI system page - Controls, Evidence & Findings", links: [{ label: "Open AI Inventory", href: "/ai-inventory" }],
    human: "Control owners and analysts submit evidence.",
    output: "Evidence submitted against a control.", next: "Human evidence review." },
  { n: 11, title: "Human Evidence Review", status: "AVAILABLE",
    what: "A reviewer accepts or rejects submitted evidence with a rationale.",
    why: "AI can help read and summarise evidence, but only a human can accept it as sufficient.",
    area: "Pending Reviews", links: [{ label: "Go to Pending Reviews", href: "/reviews/pending" }],
    human: "An independent reviewer decides. You cannot review evidence you submitted.",
    output: "Accepted or rejected evidence, with history.", next: "Test the control." },
  { n: 12, title: "Control Testing", status: "AVAILABLE",
    what: "Test design effectiveness and operating effectiveness, validate the evidence, and record the result.",
    why: "Accepted evidence shows a control exists; testing shows it actually works.",
    area: "Control evidence page - Control testing", links: [{ label: "Open AI Inventory", href: "/ai-inventory" }],
    human: "An independent tester (not the control owner) performs and completes the test.",
    output: "A locked test result (effective, partially effective, ineffective).", next: "Raise a Finding if deficient." },
  { n: 13, title: "AI Finding", status: "AVAILABLE",
    what: "A deficient test, missing evidence, monitoring signal or governance issue becomes a documented Finding with a severity.",
    why: "Findings make gaps visible and trackable instead of forgotten.",
    area: "Findings", links: [{ label: "Go to Findings", href: "/findings" }],
    human: "A person creates the Finding and judges its severity.",
    output: "A Finding pending review.", next: "Human Finding review." },
  { n: 14, title: "Human Finding Review", status: "AVAILABLE",
    what: "A reviewer confirms the Finding (it becomes Open) or dismisses it, with a rationale.",
    why: "AI may propose; a human reviewer decides what is real.",
    area: "Pending Reviews / Findings", links: [{ label: "Go to Pending Reviews", href: "/reviews/pending" }],
    human: "An independent reviewer decides. You cannot review a Finding you created.",
    output: "Confirmed (Open) or dismissed Finding.", next: "Decide treatment." },
  { n: 15, title: "Treatment Decision", status: "AVAILABLE",
    what: "Decide what to do about the risk: remediate, accept (where authorised), request more evidence, or record not applicable.",
    why: "Every confirmed gap needs an explicit, owned decision.",
    area: "AI risk assessment - Treatment plan (owner and target date)", links: [{ label: "Go to Risk Register", href: "/risk-register" }],
    human: "An accountable owner is assigned; the treatment is a recorded human decision.",
    output: "A treatment plan with owner and target date.", next: "Remediate or accept." },
  { n: 16, title: "Remediation OR Risk Acceptance", status: "AVAILABLE",
    what: "Remediation fixes the issue and collects evidence of the fix. Risk Acceptance is a formal, time-bound decision by an authorised human to tolerate the remaining risk, with rationale.",
    why: "Two legitimate paths - but both must be explicit and evidenced. AI cannot accept risk.",
    area: "Remediation; Risk Acceptance", links: [{ label: "Go to Remediation", href: "/remediation" }, { label: "Go to Risk Acceptance", href: "/risk-acceptance" }],
    human: "Owners remediate; an independent, authorised reviewer decides risk acceptance (not the requester).",
    output: "Remediation record or Risk Acceptance decision.", next: "Verify." },
  { n: 17, title: "Verification / Approval", status: "AVAILABLE",
    what: "An independent verifier confirms the remediation worked (closing the Finding) or rejects it back to In Progress.",
    why: "\"Done\" is a claim until someone else verifies it.",
    area: "Finding remediation - independent verification", links: [{ label: "Go to Findings", href: "/findings" }],
    human: "The remediation owner cannot verify their own work (separation of duties).",
    output: "Verified and closed remediation and Finding.", next: "Reassess when things change." },
  { n: 18, title: "Reassessment", status: "AVAILABLE",
    what: "Start a new governance cycle when risk, controls or the AI change, evidence expires, monitoring flags a concern, a Risk Acceptance nears expiry, or a scheduled review is due.",
    why: "AI governance is not one-time. Earlier records stay as history; changes become new versions.",
    area: "Reassessments", links: [{ label: "Go to Reassessments", href: "/reassessments" }],
    human: "An authorised person starts and concludes the reassessment with a rationale.",
    output: "A completed, locked reassessment record.", next: "Keep monitoring." },
  { n: 19, title: "Production Governance Monitoring", status: "AVAILABLE",
    what: "Define what must be reviewed, by whom and how often (for example human-override rates or complaints), and record human observations.",
    why: "Governance continues while the AI is in use. VendorGuard organises governance signals and evidence - it is not a SIEM, SOC, EDR, CSPM or runtime AI firewall.",
    area: "Governance Monitoring", links: [{ label: "Go to Governance Monitoring", href: "/governance-monitoring" }],
    human: "Check owners record reviews; escalation to reassessment is an explicit human action.",
    output: "Monitoring checks and review history.", next: "Respond to significant events." },
  { n: 20, title: "AI Incident", status: "AVAILABLE",
    what: "A significant AI-related event that triggers governance response: findings, reassessment, remediation and reporting.",
    why: "Incidents test whether governance works under pressure and feed lessons back into controls.",
    area: "AI Incident Management", links: [{ label: "AI Incidents", href: "/ai-incidents" }],
    human: "Humans declare, investigate and close incidents.",
    output: "An incident record linked to governance actions.", next: "Reassess or remediate.",
    note: "Manual incident registration, investigation, response and independent closure review are available. Link evidence, existing findings and explicit reassessments." },
  { n: 21, title: "Retirement", status: "PLANNED",
    what: "Retire an AI system in a controlled way: approval, final evidence, access removal, dependency review, record retention, audit trail and final lifecycle state.",
    why: "Retired AI can leave data, access and dependencies behind. Ending governance is itself a governed step.",
    area: "AI Retirement", links: [],
    human: "An accountable owner requests retirement; an authorised person approves it.",
    output: "A retirement record with closure evidence.", next: "Records retained for audit.",
    note: "A controlled AI Retirement workflow is a planned VendorGuard capability." },
];

export const AI_TPRM_STAGES: GuideStage[] = [
  { n: 1, title: "AI Vendor Intake", status: "AVAILABLE",
    what: "Identify the external AI provider: who they are, what is being bought and why the business needs it.",
    why: "Third-party AI brings the provider's risks into your organisation.",
    area: "Vendor Inventory", links: [{ label: "Go to Vendor Inventory", href: "/vendors-list" }],
    human: "An analyst registers the vendor and the business justification.",
    output: "An AI vendor record.", next: "Identify the AI service." },
  { n: 2, title: "Identify AI Service / Dependency", status: "AVAILABLE",
    what: "Record the AI product or model provider, business use, data exchanged, integration and criticality.",
    why: "The risk depends on what the AI service touches and how much the business depends on it.",
    area: "Vendor profile (AI product type, AI providers, data use); AI system page - third-party dependencies", links: [{ label: "Go to Vendor Inventory", href: "/vendors-list" }, { label: "Link to an AI system", href: "/ai-inventory" }],
    human: "An analyst records the facts; the business owner confirms the use.",
    output: "AI service details and links to AI systems in the inventory.", next: "Assess the vendor." },
  { n: 3, title: "AI Vendor Assessment", status: "AVAILABLE",
    what: "Start a structured assessment of the AI provider against selected frameworks.",
    why: "Verify, don't assume, how the provider manages the risks of its AI service.",
    area: "Vendor Assessments", links: [{ label: "Go to Vendor Assessments", href: "/assessments" }],
    human: "An analyst starts and runs the assessment.",
    output: "An assessment workspace for the vendor.", next: "Due diligence." },
  { n: 4, title: "AI Risk / Due Diligence", status: "AVAILABLE",
    what: "Cover data handling, privacy, security, model and service governance, reliability, regulatory exposure, subcontractors, human oversight and contractual concerns.",
    why: "Due diligence turns concerns into evidence-backed answers. It is governance review, not penetration testing.",
    area: "Vendor Assessments - AI vendor questionnaire and configurable risk rating", links: [{ label: "Go to Vendor Assessments", href: "/assessments" }],
    human: "The analyst completes the questionnaire; an independent reviewer reviews and approves it.",
    output: "Questionnaire responses and a recorded risk rating.", next: "Determine requirements." },
  { n: 5, title: "Applicable Requirements / Controls", status: "AVAILABLE",
    what: "Map the vendor to the frameworks and controls that actually apply, based on what the AI service does and what data it touches.",
    why: "One generic checklist does not fit every AI provider.",
    area: "Compliance Frameworks; assessment framework mapping", links: [{ label: "Compliance Frameworks", href: "/frameworks" }],
    human: "The analyst decides which requirements apply.",
    output: "Requirement-to-control mapping for the assessment.", next: "Collect evidence." },
  { n: 6, title: "Evidence Collection", status: "AVAILABLE",
    what: "Collect SOC reports, policies, certifications, AI documentation, security and privacy documentation, contractual evidence and architecture information.",
    why: "Independent documentation verifies the vendor's claims.",
    area: "Vendor Evidence Library (open a vendor - View Evidence)", links: [{ label: "Go to Vendor Inventory", href: "/vendors-list" }],
    human: "Analysts upload evidence; access follows evidence permissions (auditors see metadata only).",
    output: "An evidence library per vendor.", next: "Analyse evidence." },
  { n: 7, title: "Evidence Analysis", status: "AVAILABLE",
    what: "VendorGuard AI can summarise evidence, identify gaps, recommend actions and propose findings.",
    why: "AI speeds up reading. AI analysis is advisory - human review remains authoritative.",
    area: "Assessment - AI evidence analysis", links: [{ label: "Go to Vendor Assessments", href: "/assessments" }],
    human: "An analyst runs the analysis; every proposal requires human review.",
    output: "AI-proposed findings marked as requiring human review.", next: "Findings." },
  { n: 8, title: "Findings", status: "AVAILABLE",
    what: "Evidence gaps and assessment issues become documented findings with a control status.",
    why: "Findings capture the residual risk that remains after controls and evidence.",
    area: "Vendor Assessments - control status and findings", links: [{ label: "Go to Vendor Assessments", href: "/assessments" }],
    human: "Analysts propose findings.",
    output: "Proposed findings per control.", next: "Human review." },
  { n: 9, title: "Human Review", status: "AVAILABLE",
    what: "A reviewer accepts, rejects, overrides, requests more evidence or marks not applicable - with a rationale.",
    why: "AI may propose; an authorised human decides.",
    area: "Finding review queue", links: [{ label: "Go to finding reviews", href: "/governance/reviews" }],
    human: "An authorised reviewer decides; record-level separation-of-duties rules are enforced by the platform.",
    output: "Recorded human review decisions.", next: "Treat the risk." },
  { n: 10, title: "Remediation / Treatment", status: "AVAILABLE",
    what: "Vendor remediation, an internal compensating action, more evidence, or risk acceptance where authorised.",
    why: "Every confirmed gap needs an owned, tracked response.",
    area: "Remediation", links: [{ label: "Go to Remediation", href: "/remediation" }],
    human: "Owners act; authorised humans make treatment and acceptance decisions.",
    output: "Tracked remediation with status.", next: "Monitor and reassess.",
    note: "Vendor-level risk acceptance exists in the platform API but has no screen yet; AI system risk acceptance is available under Risk Acceptance." },
  { n: 11, title: "Monitoring / Reassessment", status: "PLANNED",
    what: "Ongoing review of material vendor changes, new AI capabilities, expired evidence, risk changes, incidents, contract changes and reassessment dates.",
    why: "Approval is not the end - AI vendors change their models and terms over time.",
    area: "Vendor monitoring", links: [],
    human: "Analysts track triggers and start reassessment.",
    output: "Reassessment triggers and schedules.", next: "Report.",
    note: "Dedicated AI vendor monitoring is a planned VendorGuard capability. AI systems that depend on a vendor can already be monitored through Governance Monitoring and Reassessments." },
  { n: 12, title: "Reporting", status: "AVAILABLE",
    what: "Executive AI vendor risk reports and audit-ready documentation.",
    why: "Leaders and auditors need a clear, evidence-backed view of third-party AI risk.",
    area: "Vendor Executive Report (open a vendor - View Executive Report, PDF export)", links: [{ label: "Go to Vendor Inventory", href: "/vendors-list" }],
    human: "Humans review and present the report; the report summarises recorded human decisions.",
    output: "Executive report and PDF.", next: "Continue monitoring." },
];